### PR TITLE
posts is now a collection

### PR DESCRIPTION
**Pull request by nhoizey**
https://github.com/jekyll/jekyll/issues/4199#issuecomment-160433348

### CODE REVIEW

**Comment by aarongustafson** [comment]
I am still running Octopress which is Jekyll 2. Can you re-write to support both the old and new approaches?

**Comment by nhoizey** [comment]
Ok, working on it!

**Comment by nhoizey** [comment]
Done.

Tested on Jekyll 3.

**Comment by aarongustafson** [comment]
I have incorporated your changes into the forthcoming gem.

**Pull request closed without merging**
