### PR TITLE
feat: Template tweaks

### PR DESCRIPTION
**Pull request by l0b0**

### CODE REVIEW

**Comment by fancypantalons** [comment]
These look like good changes, but I noticed you've only modified the `webmentions` template.  Would you mind performing similar cleanup/improvement to the other templates so they function consistently?  For example, the `likes` template also links to the author URL but I agree with your change in that it shouldn't if the URL isn't provided.

**Comment by l0b0** [comment]
I'm a bit torn. There are very few tests, I'm not a Ruby whiz, and this sort of improvement touches almost every line of every template. Would you be OK to create some failing tests of how you would want various Webmentions content to be rendered? Then I can be sure we're both on the same page *and* that I don't accidentally break anything.

**Comment by fancypantalons** [comment]
Heh, ngl, while writing more test automation has been on the list for a *very* long time, it's not something I plan to prioritize any time soon.  What can I say, I'm an iconoclast. ;)  And the reality is this is pretty low risk stuff as I suspect most folks customize the templates pretty quickly once they get webmentions enabled.

Really it's just a matter of consistency across the templates, though tbf, the templates are already horribly inconsistent (the posts template, for example, looks completely different from the general webmention template).

I think what I'll do is create a new ticket to normalize/standardize the templates and I can look at incorporating these changes into that work stream.

**Comment by fancypantalons** [comment]
Alright, so just pushed 63559f11.  Feel free to take a look.  I've run local tests on my own webmention collection and things look good, but another set of eyes can't hurt.

That commit does a bunch of stuff to both standardize the templates, fix the url/uri problem you spotted, and also handle the edge cases you've identified in this PR.

**Comment by l0b0** [comment]
Yeah, that's much better! Is there any value left in this PR? Otherwise you can just close it.

**Comment by fancypantalons** [comment]
At this point, yeah, I think we can probably kill the PR, assuming there aren't other changes/cleanups you might suggest in that area of code (though, regardless, the PR would have to be reworked since the underlying code is changed so much).

**Pull request closed without merging**
