### PR TITLE
Fix Deprecation: posts.each should be changed to posts.docs.each.

### PR DESCRIPTION
**Pull request by alias1**
Not sure if this should have a guard on it so it works for Jekyll 2.x and 3.x..? If so.. what should be added?

### CODE REVIEW

**Comment by aarongustafson** [comment]
Yes. We need to guard for Jekyll 2 as a lot of Octopress installs (including mine) still run it.

**Comment by alias1** [comment]
That's fair. Have you rolled this into one of the other  changes you made already? Or should I figure a good guard and send another PR?

Sent from Outlook Mobile




On Mon, Apr 18, 2016 at 10:29 AM -0700, "Aaron Gustafson" <notifications@github.com> wrote:












Closed #9.

**Comment by aarongustafson** [comment]
If you could take a stab at it… :-)

**Comment by alias1** [comment]
Can do. Want me to just do it on the 'convert to gem' PR? Probably less effort overall.

**Comment by aarongustafson** [comment]
Sure.

On Monday, April 18, 2016, alias1 <notifications@github.com> wrote:

> Can do. Want me to just do it on the 'convert to gem' PR? Probably less
> effort overall.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/aarongustafson/jekyll-webmention_io/pull/9#issuecomment-211537777>
>


-- 
Cheers,

Aaron

**Comment by alias1** [comment]
Coolies

Sent from Outlook Mobile




On Mon, Apr 18, 2016 at 12:52 PM -0700, "Aaron Gustafson" <notifications@github.com> wrote:










Sure.



On Monday, April 18, 2016, alias1 <notifications@github.com> wrote:



> Can do. Want me to just do it on the 'convert to gem' PR? Probably less

> effort overall.

>

> —

> You are receiving this because you modified the open/close state.

> Reply to this email directly or view it on GitHub

> <https://github.com/aarongustafson/jekyll-webmention_io/pull/9#issuecomment-211537777>

>





-- 

Cheers,



Aaron

**Pull request closed without merging**
