### PR TITLE
Syndication

### PR DESCRIPTION
**Pull request by aarongustafson**
Dupes #134 to main

### CODE REVIEW

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.

**Comment by fancypantalons** [comment]
> 👋🏼 Brett,
> 
> Is this "feature complete"?
> 
> I can install from your branch, but Brid.gy does not appear to be sending webmentions through the plugin.
> 
> Is this just missing documentation on how to configure or did I miss a step?
> 
> The relevant commit is at [this](https://github.com/chrisfinazzo/blog/commit/d03f3d1c63fb408f24284907775abdf7907d1044) URL.

Wow, apologies for the *very* late reply!

Yup, this feature is complete!  I use it for syndicating my posts to Twitter via Brid.gy on my own blog.

I don't see anything immediately wrong with your configuration.  After calling `jekyll build`, if you look in your cache directory, are there any entries in `webmention_io_outgoing.yml` indicating a queued outgoing webmention?

**Comment by chrisfinazzo** [comment]
```
---
https://chrisfinazzo.com/2018/04/11/minimum-viable-writing-product/:
  https://chrisfinazzo.github.io: false
  https://www.youtube.com/watch?v=prkBmmFQcEw: false
https://chrisfinazzo.com/2018/04/13/adventures-in-rsync/: {}
https://chrisfinazzo.com/2018/04/16/drunk-with-power/:
  https://www.instagram.com/p/Bhoxl5iBgQP/?taken-by=chrisfinazzo: false
https://chrisfinazzo.com/2018/04/20/a-desk-and-a-chair/:
  https://www.fully.com/standing-desks/jarvis/jarvis-adjustable-height-desk-bamboo.html: false
  https://www.amazon.com/dp/B00HFT9KI2: false
  ? https://www.google.com/search?ei=GWDaWvzGK8Ps5gLpp6jYAg&q=lumbar+pillow&oq=lumbar+pillow&gs_l=psy-ab.12...0.0.0.4130.0.0.0.0.0.0.0.0..0.0....0...1..64.psy-ab..0.0.0....0.ONoCeX0WODA
  : false
https://chrisfinazzo.com/2018/04/23/invalid/:
  https://twitter.com/adactio: false
  https://abookapart.com/products/going-offline: false
https://chrisfinazzo.com/2018/04/28/security-by-deletion/:
  https://github.com/jekyll/minima/pull/234: false
https://chrisfinazzo.com/2018/05/01/going-offline/:
  https://chrisfinazzo.com/sw.js: false
https://chrisfinazzo.com/2018/05/06/sites-on-the-cheap/:
  https://github.com/parkr/stuff: false
  https://github.com/octopress/linkblog: false
  https://github.com/chrisfinazzo/jekyll-scripts: false
https://chrisfinazzo.com/2018/05/14/ssh-for-humans/:
  https://twitter.com/antichrista/status/994270747567669248: false
  https://twitter.com/antichrista: false
  https://github.com/chrisfinazzo/microblog/blob/master/gulpfile.js: false
https://chrisfinazzo.com/2018/05/19/where-were-going/:
  http://talk.jekyllrb.com: false
  http://octopress.org: false
  https://github.com/octopress/linkblog: false
  http://atp.fm/96: false
https://chrisfinazzo.com/2018/05/31/sixty-percent-keyboard/:
  http://zacbir.net/2018/05/24/elegance-distilled-the-60-apple-extended-keyboard-ii/: false
  https://thewirecutter.com/reviews/our-favorite-mechanical-keyboards/: false
https://chrisfinazzo.com/2018/06/13/future-of-safari-extensions/:
  https://developer.apple.com/videos/play/wwdc2018/234/: false
  https://en.wikipedia.org/wiki/Windows_Registry: false
  https://shauninman.com/archive/2012/01/19/detox: false
  https://daringfireball.net/linked/2011/07/27/josh-clark: false
  https://code.google.com/archive/p/jsblacklist/downloads: false
  http://aichon.com/dumpbox/extensions/: false
  https://chrome.google.com/webstore/category/extensions?hl=en-US&_feature=free: false
https://chrisfinazzo.com/2018/06/25/a-brief-reprieve/:
  https://chrisfinazzo.com/2018/06/13/future-of-safari-extensions/: false
  http://www.barebones.com: false
  https://en.wikipedia.org/wiki/Property_list: false
  https://twitter.com/hisaac/status/1007693058824179712: false
  https://www.youtube.com/watch?v=HMqZ2PPOLik: false
  http://5by5.tv/hypercritical/29: false
https://chrisfinazzo.com/2019/01/08/books-2018/:
  https://twitter.com/imcatnoone/status/1080169804277911552: false
  https://twitter.com/blehnert/status/1079452628797530113: false
  https://twitter.com/agisilaosts/status/1079465437929320448: false
  https://www.audible.com: false
  https://www.goodreads.com/user/show/16467089-chris-finazzo: false
  https://www.amazon.com/Young-Money-Streets-Post-Crash-Recruits/dp/044658326X: false
  https://www.amazon.com/Big-Short-Inside-Doomsday-Machine/dp/0393072231: false
  https://abookapart.com/products/the-new-css-layout: false
  https://abookapart.com/products/going-offline: false
  https://www.amazon.com/Too-Big-Fail-Washington-System/dp/0670021253: false
  https://abookapart.com/products/accessibility-for-everyone: false
  https://www.amazon.com/Flash-Boys-Wall-Street-Revolt/dp/0393351599: false
  https://www.amazon.com/Becoming-Steve-Jobs-Evolution-Visionary/dp/0385347421: false
  https://www.amazon.com/Colossal-Failure-Common-Sense-Collapse/dp/0307588335: false
  https://www.amazon.com/Straight-Hell-Deviance-Debauchery-Billion-Dollar/dp/0802123309: false
  https://www.amazon.com/Accidental-Billionaires-Founding-Facebook-Betrayal/dp/0307740986: false
  https://www.amazon.com/Steve-Jobs-Walter-Isaacson/dp/1451648537/: false
  https://www.amazon.com/Into-Thin-Air-Personal-Disaster/dp/0385494785: false
  https://www.amazon.com/What-Happened-Hillary-Rodham-Clinton/dp/1501175564: false
  https://www.amazon.com/The-Fifth-Risk/dp/B07GNTDQJQ: false
  https://www.amazon.com/The-Coming-Storm/dp/B07FHLQ2DD: false
https://chrisfinazzo.com/2019/04/22/make-all/:
  https://www.npmjs.com/package/gulp-shell: false
  https://news.ycombinator.com/item?id=19086197: false
https://chrisfinazzo.com/2020/02/20/drafts-in-six-lines-of-code/:
  https://www.youtube.com/watch?v=8SUkrR7ZfTA: false
https://chrisfinazzo.com/2020/04/07/social-distancing-pt1-hello-zsh/:
  https://support.apple.com/kb/HT208050.: false
  https://www.hopkinsmedicine.org/health/conditions-and-diseases/coronavirus/coronavirus-social-distancing-and-self-quarantine: false
  https://support.apple.com/en-us/HT208050: false
  https://scriptingosx.com/2019/11/new-book-release-day-moving-to-zsh/: false
  https://github.com/chrisfinazzo/dotfiles: false
  https://cdn.tyler.io/wp-content/uploads/2019/10/8DF8764D-61E2-49BC-8548-8A864EAF3F9F.jpeg: false
https://chrisfinazzo.com/2020/04/08/social-distancing-pt2-adventures-in-continuous-integration/:
  https://giphy.com/embed/8y8NVqFqhTQVa: false
  https://giphy.com/gifs/ratatouille-admin-billy-boyd-8y8NVqFqhTQVa: false
  https://giphy.com/embed/H4qKN0dHfkZAA: false
  https://giphy.com/gifs/technology-dazed-dazedvrt1-H4qKN0dHfkZAA: false
  https://giphy.com/embed/zaqclXyLz3Uoo: false
  https://giphy.com/gifs/zaqclXyLz3Uoo: false
  https://www.netlify.com: false
  https://en.wikipedia.org/wiki/TOML: false
  https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP: false
  https://en.wikipedia.org/wiki/Single-page_application: false
  https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API: false
  https://docs.netlify.com/functions/overview/: false
  https://pages.github.com/: false
  https://www.heroku.com/: false
  https://statically.io/: false
https://chrisfinazzo.com/2020/04/20/social-distancing-pt3-a-better-linkblog/:
  https://www.manton.org/2016/03/03/the-evolution-of.html: false
  https://jekyllrb.com/docs/collections/: false
  https://jekyllrb.com/docs/datafiles/: false
https://chrisfinazzo.com/2020/04/26/social-distancing-pt4-when-government-almost-gets-it-right/:
  https://giphy.com/embed/xTiN0DvoDyWQey2B8I: false
  https://giphy.com/gifs/nbc-nbc-90-90th-special-xTiN0DvoDyWQey2B8I: false
  https://twitter.com/chrisfinazzo/status/1235222740669521925: false
  https://www.sesamestreet.org/caring: false
  https://www.youtube.com/watch?v=KZmLI7eYjmw: false
  https://my2020census.gov: false
  https://www.usds.gov: false
  https://18f.gsa.gov: false
  https://www.gov.uk: false
https://chrisfinazzo.com/2020/05/06/social-distancing-pt5-indieweb-inside-out/:
  https://github.com/sferik/twitter: false
  https://en.wikipedia.org/wiki/Why_Don: false
  https://twitter.com/hotdogsladies: false
  https://www.urbandictionary.com/define.php?term=OG: false
  https://indieweb.org: false
  https://indieweb.org/POSSE: false
  https://brid.gy: false
  https://indieweb.org/Webmention: false
  https://www.youtube.com/watch?v=ZOlkS6xP2Zk&list=FLIQvUB7irH0nP08FvfkrZvw: false
  https://github.com/cliss/camel: false
  https://indieweb.org/Micropub: false
  https://webmention.app: false
  https://remysharp.com: false
https://chrisfinazzo.com/2020/05/14/social-distancing-pt6-not-quite-language-agnostic/:
  https://byparker.com/blog/2015/language-agnostic-interfaces-for-software-development/: false
  https://github.com/chrisfinazzo/rake-jekyll: false
  https://en.wikipedia.org/wiki/PdfTeX: false
  https://en.wikipedia.org/wiki/XeTeX: false
  https://en.wikipedia.org/wiki/GNU_Aspell: false
  http://www.macdrifter.com/2012/01/custom-grammar-checker-in-bbedit.html: false
  http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/: false
  https://dbader.org/blog/spell-checking-latex-documents-with-aspell: false
  https://tex.stackexchange.com/questions/42843/is-there-a-spell-check-package-for-latex?noredirect=1&lq=1: false
  https://imgs.xkcd.com/comics/automation.png: false
  https://github.com/chrisfinazzo/resume/commit/1128992b3582fe60be9511354341d1e90d6c3d9e: false
https://chrisfinazzo.com/2020/05/18/social-distancing-pt7-escape-hatch/:
  https://giphy.com/embed/y6Lgj4yTpMmZO: false
  https://giphy.com/gifs/tiger-woods-y6Lgj4yTpMmZO: false
  https://github.com/Homebrew/homebrew-core/issues/38213: false
  https://en.wikipedia.org/wiki/Data_science: false
  https://dotfiles.github.io: false
  https://chrisfinazzo.com/2020/04/07/social-distancing-pt1-hello-zsh/: false
  https://ohmyz.sh: false
  https://github.com/sorin-ionescu/prezto: false
  https://twitter.com/chrisfinazzo/status/1100065027887951873: false
  https://www.apple.com/macbook-pro-13/: false
https://chrisfinazzo.com/2020/06/03/social-distancing-pt8-reading-list/:
  http://www.cagrimmett.com/development/2019/09/07/reading-list.html: false
  https://frankchimero.com: false
  http://jsomers.net/: false
  https://github.com/chrisfinazzo/blog/blob/master/_data/reading.yml: false
https://chrisfinazzo.com/2021/03/25/test/:
  http://www.cagrimmett.com/development/2019/09/07/reading-list.html: false
  https://frankchimero.com: false
  http://jsomers.net/: false
  https://github.com/chrisfinazzo/blog/blob/master/_data/reading.yml: false
```

It's all there, but it seems like even if my config is 👌🏼, I missed a step somewhere. I expected that inserting a link in the test Markdown file was enough to trigger Brid.gy...

Seems like this is not the case?

**Comment by chrisfinazzo** [comment]
Re-upping this now that I'm giving it another look. I'm running the dev branch version of JW if that helps...

Setup is a follows:

Jekyll 3.9.2
Ruby 2.7.0

`_config.yml`

    feed:
      path: notes-rss.xml

    webmentions:
      collections:
        - notes
      syndication:
        mastodon:
          endpoint: https://brid.gy/publish/mastodon

`_layouts/note.html`

```
<article class="h-entry">
<h1 class="p-name"><a class="u-url" href="{{ page.url }}">{{ page.title }}</a></h1>
<div class="meta"><time datetime="{{ page.date | date: "%Y-%m-%d" }}" class="dt-published">{{ page.date | date: '%B %-d, %Y' }}</time></div>
<div class="e-content">
{{ content }}
</div>
<a href="https://brid.gy/publish/mastodon?bridgy_omit_link=true"></a>
</article>

```
Creating a file in `_notes` with the following content will generate a curl command to send the webmention (lookups and queueing are done in my build task):

```
---
layout: note
title: Another Test
syndicate_to: [ mastodon ]
---

With any luck, this note will find its way to [Mastodon][].

[Mastodon]: https://joinmastodon.org

```

One thing that comes to mind is that my deploys are not automatically published when Netlify builds and runs the webmention [plugin][]. Could this be tripping up Brid.gy's post discovery? (👀 @snarfed)

[plugin]: https://github.com/CodeFoodPixels/netlify-plugin-webmentions

**Comment by snarfed** [comment]
@chrisfinazzo sorry, I don't quite follow the problem here, other than your posts aren't triggering Bridgy Publish? You can see attempts on your Bridgy user page, and I'm happy to check logs too if you want.

**Comment by chrisfinazzo** [comment]
> @chrisfinazzo sorry, I don't quite follow the problem here, other than your posts aren't triggering Bridgy Publish? You can see attempts on your Bridgy user page, and I'm happy to check logs too if you want.

That's what I'm seeing. Although it was slightly delayed, I did get a `200` response to [this][] request. Is it necessary to include `u-syndication` with a hyperlink in order for this to work automatically?

I'm not doing this bit currently, but it brings up a question of how to add these links if the post being syndicated doesn't actually exist on the service. IOW, I'm guessing until the post hits Mastodon, that URL isn't known yet to Brid.gy yet?

Happy to be proven wrong...

[this]: https://brid.gy/log?start_time=1674586448&key=agdicmlkLWd5cl4LEg1QdWJsaXNoZWRQYWdlIjdodHRwczovL2NocmlzZmluYXp6by5jb20vbm90ZXMvMjAyMy8wMS8yNC9hbm90aGVyLXRlc3QvDAsSB1B1Ymxpc2gYgIDYhOKclwkM&module=default

**Comment by chrisfinazzo** [comment]
Hmmm....

Brid.gy says "published", but it doesn't reach Mastodon.

Log is [here][].

[here]: https://brid.gy/log?start_time=1675267855&key=agdicmlkLWd5clkLEg1QdWJsaXNoZWRQYWdlIjJodHRwczovL2NocmlzZmluYXp6by5jb20vbm90ZXMvMjAyMy8wMi8wMS9hbm90aGVyLwwLEgdQdWJsaXNoGICA2LSJhIILDA&module=default

**Comment by snarfed** [comment]
Hi @chrisfinazzo! Looks like that was just a preview; the line for it in the "Published" section on https://brid.gy/mastodon/@chrisfinazzo@mastodon.social says _preview_. If you preview it again and click _Send_, it should go through.

**Comment by fancypantalons** [comment]
FYI, I've been doing a bunch of refactoring on the main branch and am closing this PR and opening a new one based on the current main branch.  After that, I expect to push the code into main fairly soon, I just wanna run it a bit, first, to make sure I've shaken out any potential rebasing bugs.

**Pull request closed without merging**
