### PR TITLE
Support for RSVP type

### PR DESCRIPTION
**Pull request by calumryan**
Proposed support for RSVP type Webmentions to be used in event pages. Not sure of Google+ support for this in activity types.

### CODE REVIEW

**Comment by aarongustafson** [comment]
Thank you for this. I won't have time to take a peek until next week, but I will look at it.

**Comment by calumryan** [comment]
@aarongustafson any progress with this?  :)

**Comment by aarongustafson** [comment]
My apologies for the delay getting back to this. I am making a few other modifications to the project and will look to work these in as part of that. I’ll let you know if there are things I need you to adjust.

**Comment by aarongustafson** [comment]
There are too many conflicts for this to merge in cleanly. Do you want to rebase from Master and re-submit or would you rather me try to manually merge it?

**Comment by calumryan** [comment]
Closing this for now and will submit new request on the latest release when I've some more time to review

**Pull request closed without merging**
