### PR TITLE
Various minor updates

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
- Readme updated from `gems` to `plugins`

- Safe navigation added to _.rb when `name` is nil. This prevents a Liquid Exception when {% webmentions %} is added to a page without a tag.
    `Liquid Exception: undefined method 'split' for nil:NilClass in /_layouts/post.html` becomes
    `[jekyll-webmention_io] Jekyll::WebmentionIO::WebmentionsTag No data provided`

- Sets `strict_variables` to` false` to suppress Liquid Errors - e.g. 
    `[jekyll-webmention_io] Liquid error: undefined variable author`

### CODE REVIEW

**Comment by aarongustafson** [comment]
Nice, thanks! I didn’t realize `&` could be used to suppress errors. I imagine there are a bunch of places that could be used in place of some of my testing conditionals.

**Comment by nhoizey** [comment]
@aarongustafson @stuartbreckenridge 

IMHO, it's even not necessary to add the plugin in the `_config.yml` file if it is in a `:jekyll_plugins` group in the `Gemfile`.

This is what I recommend for [the installation of my jekyll-cloudinary plugin](https://github.com/nhoizey/jekyll-cloudinary#installation):

> Add gem 'jekyll-cloudinary' to the jekyll_plugin group in your Gemfile:
>
>     source 'https://rubygems.org'
>     
>     gem 'jekyll'
>     
>     group :jekyll_plugins do
>       gem 'jekyll-cloudinary'
>     end
> 
> Then run bundle update to install the gem.

**Comment by aarongustafson** [comment]
@nhoizey You’re right, it gets picked up automatically.

**Comment by nhoizey** [comment]
Great!

**Pull request merged**
