### PR TITLE
Fix problem with ordered list markup creating invalid HTML

### PR DESCRIPTION
**Pull request by dltj**
Fixes https://github.com/aarongustafson/jekyll-webmention_io/issues/148

### CODE REVIEW

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.

**Comment by fancypantalons** [comment]
Honestly, I have a much bigger concern that we're getting untrusted, third party content in the form of webmentions, and we're passing it through a markdown parser.  I need to look at the history and code flow, here, as, naively, that seems strange to me...

**Comment by fancypantalons** [comment]
I'm gonna close this PR as I believe the actual, proper fix, here, is to stop running webmention content through a markdown parser in the first place, as at least with webmention.io, we're gonna receive text or sanitized HTML, not markdown.

**Comment by aarongustafson** [comment]
Sounds good. The Markdown parsing predated HTML in the feed.

**Comment by dltj** [comment]
> I'm gonna close this PR as I believe the actual, proper fix, here, is to stop running webmention content through a markdown parser in the first place, as at least with webmention.io, we're gonna receive text or sanitized HTML, not markdown.

Makes sense—thanks for your efforts, @fancypantalons.

**Pull request closed without merging**
