### PR TITLE
Convert to gem

### PR DESCRIPTION
**Pull request by alias1**
Got the JS file from gem -> built site working with a generator.
Fixed up the cache path stuff to work from the gem.
Created JS liquid tag: `webmention_js_tag`
Created liquid tag: `webmention_redirected_from`
Converted the rake task to a jekyll command: `jekyll webmention`

Related to #3 
Solves #7

### CODE REVIEW

**Comment by aarongustafson** [comment]
Phew, this is a lot to parse (and test). I have some changes I am merging into the master branch to handle the `curl` vulnerabilities. Once those are in (and I take care of a few other unrelated things) I will start looking it over. It will probably be Wednesday or Thursday of this week.

**Comment by alias1** [comment]
That's cool, no rush :)

Will probably have to roll those curl changes into this, and can't remember if I fixed it here or not but may need to guard the deprecated thing I mentioned in the other thread. And then a bit of a diff across current master and this to make sure nothing slipped through.

Hopefully this layout should make future stuff way easier to work with but :)

**Comment by aarongustafson** [comment]
Yeah, I realized that last push was a bit bigger than I remembered.
Webmention.io and Brid.gy have changed some things so I had to add some
branches in the code to handle them and the fun things Google+ does. I also
ported those changes over to the JS so the functionality is mirrored for
post-deployment webmentions and streaming ones too.

BTW - I like the modularization :-)

**Comment by alias1** [comment]
That makes sense :) Yay modular!

**Comment by alias1** [comment]
Added fix for 3.x deprecation + guard for 2.x in e61e56c

**Comment by alias1** [comment]
Just wanted to follow up on this.

**Comment by aarongustafson** [comment]
Thank you so much for your work on this!

I had a lot of work to do on the plugin, so I ended up having to rewrite a lot of it, but it is close to being ready as a Gem (finally). Your work was a real inspiration, though, thank you!

PS - If you want to see where things are at, take a peek at the [gem_conversion](https://github.com/aarongustafson/jekyll-webmention_io/tree/gem_conversion) branch.

**Comment by alias1** [comment]
Awesome to hear :) Will have to have a peek.

**Pull request closed without merging**
